server:
  port: 8801
spring:
  application:
    name: infrastructure
eureka:
  instance:
    appname: infrastructure
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
  client:
      service-url:
        defaultZone: http://localhost:8800/eureka/
