server:
  port: 8803
spring:
  application:
    name: batch
eureka:
  instance:
    appname: batch
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
  client:
      service-url:
        defaultZone: http://localhost:8800/eureka/
